### ISSUE TITLE
chosen and multiple not working when 'dataContainer' => 'File',

### ISSUE THREAD

**Issue by benfolds** [contao-community-alliance/contao-multicolumnwizard-bundle#42]
**Case:**
A multiselect filed at the tl_settings. In this case i want so select one or more content elements. 

```
'selectElement' => [
                'label'     => &$GLOBALS['TL_LANG']['tl_settings']['classNames']['selectElement'],
                'inputType' => 'select',
                'default'   => 'all',
                'eval'      => [
                    'style'              => 'width:250px',
                    'chosen'             => true,
                    'multiple'           => true
                ],
                'options_callback'  => ['tl_settings_helper', 'getContentElements'],
                'reference' => &$GLOBALS['TL_LANG']['CTE'],
            ]
```

**Behaviour**
The field itself is working fine but when saving all setting inside the multicolumn wizard break. Guess the problem is saving an serialized array insinde a serialized array?

**Comment by zonky2** [comment]
wrapp code in tree ticks "```"

**Comment by discordier** [comment]
This is a problem of `DC_File` then, isn't it?

**Comment by benfolds** [comment]
hm, i guess the "normal" fields can not have nested serialized arrays, this could be only when using the multicolumnwizard, right? So maybe the array inside the array must be stored different? or you can escape the specialchars for the nested array when using this settings for this data container..

**Comment by discordier** [comment]
No, there is also (at least) the module wizard widget and checkbox wizard in the core - do these work?

**Comment by benfolds** [comment]
Just checked it:
The checkbox wizard design is broken inside the multicolumnwizard but the values will be stored correctly

**Comment by discordier** [comment]
Design is another issue.

So I fear the problem is, that file uuids are stored as binary and this simply does not work correctly when writing it to a plain PHP file.
I am sorry but I fear there is nothing we can do here, as the serialized array is correct (from PHPs point of view) but the saving and loading of `localconfig.php` seems to not cope correctly with binary (which is not a big surprise as it is a text file).

On the other hand, `localconfig.php` and the system settings in the backend are considered deprecated since Contao 4.0 and all settings shall be migrated to settings files (`config.yml` and the like) over time and therefore you should search for a better point to save your data anyway, I suggest an own database table for user editable data or a static config on the file system (using the file path instead of the id) for data only to be manipulated by the system administrator and not to be manipulated.

**Comment by benfolds** [comment]
Get your point with the localconfig.php, it's just easygoing to store system-wide info here :) It seems a bit too overengineered to store that in an own database...

But the problem there is **not** to store UUID's. I just have a dropdown of available content elements ...

**Comment by discordier** [comment]
Ah sorry, misunderstood, I thought you were storing file pickers, I don't know why...

**Comment by Total-Reality** [comment]
I can't reproduce it with Contao 4.9 & MCW 3.4.9
However I tested it with options instead of "options_callback".

Please post your complete code.

This works:
```
$GLOBALS['TL_DCA']['tl_settings']['fields']['test'] = array
(
    'inputType' => 'multiColumnWizard',
    'eval'      => array
    (
        //'columnsCallback' => array('tl_mcw_test', 'getTestFields'),
        'columnFields' => array
        (
          'text' => array
          (
            'label'              => 'text',
            'default'            => 'Bla',
            'inputType'          => 'text',
            'eval'               => array('maxlength'=>5, 'style'=>'width:50px', 'readonly'=>true) //, 'nospace'=>true, 'trailingSlash'=>true
          ),
          'select' => array
          (
            'label'              => 'select',
            'default'            => 'b',
            'inputType'          => 'select',
            'options'            => array('s' => 'Sidney', 'b' => 'Bristol'),
            'eval'               => array('chosen' => true, 'multiple' => true, 'includeBlankOption' => true)
          ),
      ),
    )
);
```

**Comment by zonky2** [comment]
works fine
